#!/bin/bash

NVIM='\033[38;2;88;147;61m'
GREEN='\033[0;32m'
RED='\033[0;31m'
NC='\033[0m'
BLUE='\033[1;34m'
PURPLE='\033[38;2;120;93;200m'

clear
echo -e "${NVIM}███╗   ██╗██╗   ██╗██╗███╗   ███╗    ███████╗███████╗████████╗██╗   ██╗██████╗ ${NC}"
echo -e "${NVIM}████╗  ██║██║   ██║██║████╗ ████║    ██╔════╝██╔════╝╚══██╔══╝██║   ██║██╔══██╗${NC}"
echo -e "${NVIM}██╔██╗ ██║██║   ██║██║██╔████╔██║    ███████╗█████╗     ██║   ██║   ██║██████╔╝${NC}"
echo -e "${NVIM}██║╚██╗██║╚██╗ ██╔╝██║██║╚██╔╝██║    ╚════██║██╔══╝     ██║   ██║   ██║██╔═══╝ ${NC}"
echo -e "${NVIM}██║ ╚████║ ╚████╔╝ ██║██║ ╚═╝ ██║    ███████║███████╗   ██║   ╚██████╔╝██║     ${NC}"
echo -e "${NVIM}╚═╝  ╚═══╝  ╚═══╝  ╚═╝╚═╝     ╚═╝    ╚══════╝╚══════╝   ╚═╝    ╚═════╝ ╚═╝     ${NC}"
echo ""

spinner() {
  local pid=$1
  local msg=$2
  local spinstr='⠋⠙⠹⠸⠼⠴⠦⠧⠇⠏'
  local i=0
  while [ -d /proc/$pid ]; do
    printf "\r${BLUE}%s${NC} %s" "${spinstr:$i:1}" "$msg"
    i=$(((i + 1) % ${#spinstr}))
    sleep 0.1
  done
  printf "\r${GREEN}✔ ${NC} %s\n" "$msg"
}
if [ "$(id -u)" -ne 0 ]; then
  echo -e "${RED}Бери sudo!${NC}" >&2
  exit 1
fi

echo ""
(apt update -qq >/dev/null 2>&1 && apt install -y fuse3 fd-find ripgrep git -qq >/dev/null 2>&1) &
spinner $! "Установка зависимостей..."
wait $!
if [ $? -ne 0 ]; then
  echo -e "${RED}Не смог поставить fuse3, чекни логи!${NC}" >&2
  exit 1
fi

(wget -q -O nvim-linux-x86_64.appimage https://github.com/neovim/neovim/releases/download/nightly/nvim-linux-x86_64.appimage) &
spinner $! "Установка Neovim..."
wait $!
if [ $? -ne 0 ]; then
  echo -e "${RED}Не смог скачать Neovim, проверь инет!${NC}" >&2
  exit 1
fi

(chmod u+x nvim-linux-x86_64.appimage) &
spinner $! "Настройка права Neovim..."
wait $!
if [ $? -ne 0 ]; then
  echo -e "${RED}Не смог дать права, что-то не так!${NC}" >&2
  exit 1
fi

mv nvim-linux-x86_64.appimage /usr/local/bin/nvim &
spinner $! "Перемещение Neovim..."
wait $!
if [ $? -ne 0 ]; then
  echo -e "${RED}Не смог переместить, проверь права!${NC}" >&2
  exit 1
fi

{
  set -e
  apt update >/dev/null 2>&1 && apt install build-essential -y >/dev/null 2>&1
  git clone https://github.com/zxc-rv/LazyVim ~/.config/nvim
} &
spinner $! "Настройка lazyvim..."
wait $!
if [ $? -ne 0 ]; then
  echo -e "${RED}Не смог настроить lazyvim, что-то пошло не так!${NC}" >&2
  exit 1
fi

(grep -q "alias vim=nvim" ~/.bashrc || echo "alias vim='nvim'" >>~/.bashrc) &
spinner $! "Добавление алиаса vim -> nvim..."
wait $!
if [ $? -ne 0 ]; then
  echo -e "${RED}Не смог добавить алиас, проверь ~/.bashrc!${NC}" >&2
  exit 1
fi
echo -e "\n${PURPLE}☑️ Neovim успешно установлен.${NC}\n"
