#!/bin/bash

GREEN='\033[0;32m'
RED='\033[0;31m'
NC='\033[0m'
BLUE='\033[1;34m'
PURPLE='\033[38;2;120;93;200m'

spinner() {
    local pid=$1
    local msg=$2
    local spinstr='⠋⠙⠹⠸⠼⠴⠦⠧⠇⠏'
    local i=0
    while [ -d /proc/$pid ]; do
        printf "\r${BLUE}%s${NC} %s" "${spinstr:$i:1}" "$msg"
        i=$(( (i+1) % ${#spinstr} ))
        sleep 0.1
    done
    printf "\r${GREEN}✔ ${NC} %s\n" "$msg"
}

echo ""
echo -e "${PURPLE}Запуск обновления Xray...${NC}"
echo ""
sleep 0.5

if [ ! -d /opt/remnawave ]; then
    echo -e "${RED}Ошибка: директория /opt/remnawave не существует${NC}"
    exit 1
fi

curl -s -L -o /tmp/Xray-linux-64.zip https://github.com/XTLS/Xray-core/releases/latest/download/Xray-linux-64.zip &
spinner $! "Скачивание релиза Xray..."

unzip -q /tmp/Xray-linux-64.zip xray -d /tmp &
spinner $! "Извлечение Xray..."

mv /tmp/xray /opt/remnawave/xray &
spinner $! "Перемещение Xray в /opt/remnawave..."

rm -rf /tmp/Xray-linux-64.zip &
spinner $! "Удаление временных файлов..."

chmod +x /opt/remnawave/xray &
spinner $! "Назначение прав на запуск Xray..."

echo -e "\n${PURPLE}☑️ Обновление Xray завершено.${NC}\n"
